In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [8]:
np.arange(10,25,5)

array([10, 15, 20])

In [9]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2,2))

array([[0.91041806, 0.96825794],
       [0.28799375, 0.58326446]])

In [13]:
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [15]:
c.shape

(2, 2, 3)

In [16]:
a.ndim

1

In [17]:
b.ndim

2

In [18]:
c.ndim

3

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
c.size

12

In [22]:
a.dtype

dtype('int32')

In [23]:
b.dtype

dtype('float64')

In [24]:
c.dtype

dtype('float64')

In [25]:
a.dtype.name

'int32'

In [26]:
b.dtype.name

'float64'

In [27]:
c.dtype.name

'float64'

In [28]:
a.astype(int)

array([1, 2, 3])

In [29]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
c.astype(int)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

In [31]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [33]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [34]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [35]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [37]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [38]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [40]:
a.sum()

np.int32(6)

In [41]:
b.sum()

np.float64(21.5)

In [42]:
c.sum()

np.float64(42.5)

In [43]:
a.min()

np.int32(1)

In [44]:
b.min()

np.float64(1.5)

In [45]:
c.min()

np.float64(1.0)

In [46]:
a.max()

np.int32(3)

In [47]:
b.max()

np.float64(6.0)

In [48]:
c.max()

np.float64(6.0)

In [49]:
a.cumsum()

array([1, 3, 6])

In [50]:
b.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [51]:
c.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5, 24.5, 26.5, 27.5, 31.5, 36.5,
       42.5])

In [52]:
a.mean()

np.float64(2.0)

In [53]:
b.mean()

np.float64(3.5833333333333335)

In [54]:
c.mean()

np.float64(3.5416666666666665)

In [56]:
np.median(a)

np.float64(2.0)

In [57]:
np.median(b)

np.float64(3.5)

In [58]:
np.median(c)

np.float64(3.5)

In [60]:
np.mod(a,b)

array([[1., 0., 0.],
       [1., 2., 3.]])

In [61]:
np.std(a)

np.float64(0.816496580927726)

In [62]:
np.std(b)

np.float64(1.5920810978785667)

In [63]:
np.std(c)

np.float64(1.6514934318838677)